### ISSUE TITLE
Remote Play broadcast pause when running game

### ISSUE THREAD

**Issue by jazmac** [smaTc/RemotePlayDetached#1]
So I installed it according to the instructions and everything works up until the point I try and remote play. It seems to think the RPD window itself is the game and anytime I switch to the actual game window (which I did start through RPD) it pauses the broadcast.

I'm guessing I'm just missing something obvious that I've done wrong.

**Comment by smaTc** [comment]
Did you start the donor game over steam?

**Comment by jazmac** [comment]
I started it through steam (I used Lego Batman as the donor game).

**Comment by smaTc** [comment]
And which app did you try to start from the launcher?

**Comment by jazmac** [comment]
Cemu emulator

**Comment by smaTc** [comment]
Hmm. Maybe enable the FPS counter in your Steam Overlay to see easily if it works. And maybe start cemu in fullscreen.

**Comment by smaTc** [comment]
Ok. Cemu's main window does not go fullscreen, maybe that is the problem. I'll try so search a workaround

**Comment by smaTc** [comment]
@jazmac 
So I tried cemu and it works.  Start the Remote Play Together Session after you start RPD. Then just open Cemu from there and launch your game. As soon as your game is running the paused broadcast notification should disappear.

**Comment by jazmac** [comment]
Sorry I didn't respond back. It turns out the donor game I was using didn't work for whatever reason. It works perfectly now after using a different game.
