### ISSUE TITLE
Compatibility with Twitch Prime

### ISSUE THREAD

**Issue by KeronCyst** [smaTc/RemotePlayDetached#12]
I'm trying to show a friend Bomber Crew in Twitch Prime. This has two hurdles:

1. It requires Twitch to open, of course; I'm not sure of whether that affects anything, though
2. It is a Unity game that pops up the little resolution-&-graphics-&-controls Unity options window before truly launching the game; I feel like this is the killer

Is this one impossible to do?

**Comment by smaTc** [comment]
1. Could be never tested it, but I also can't do anything about it if it does not work.
2. Normally all windows work. The Unity Launcher should be no problem.

**Comment by KeronCyst** [comment]
Broforce on Twitch Prime worked! But not Bomber Crew, nor another Unity game I tested for its popup window ([A Good Gardener](https://turnfollow.itch.io/a-good-gardener))... I really think it has something to do with that darn little Unity popup window, and I understand that there's probably nothing that you can do about that. Oh, well; RPD still rocks.
