### ISSUE TITLE
Ken Follet's pillars of the earth failed to start (error code 86)

### ISSUE THREAD

**Issue by SpiritBob** [smaTc/RemotePlayDetached#14]
Please fix!

I own the game in steam, and when I launch it manually from the .exe file, it successfully works. But if I do it from your .exe, it doesn't.

Other games are working fine with your assembly.

**Comment by smaTc** [comment]
More details please

**Comment by SpiritBob** [comment]
@smaTc That's the most I can give you. I literally added the game as instructed (its .exe) from a donor game (that supports RPT) and upon running it, i get the message that the game failed to start (error code 86).

If you want me to share something specific, let me know.

**Comment by smaTc** [comment]
If this is all you can give I can't really help you. But to be sure: you swapped the donor game executable with the RPD executable and then you launch rpd/donor via steam. From there you added your game and started it?

**Comment by SpiritBob** [comment]
@smaTc Yes sir!

Almost any other game I launched (Like Disco Elysium, Darkwood) works with your RPD executable, but the moment I do the same with the game "Pillars of the Earth", I get the above mentioned error code.

I don't know what else to report/explain to you other than what steam is reporting to me!

I hope you can get to the bottom of this. It's a weird bug, because it only happens on that single title. All of the games I've run I own on steam.

**Comment by smaTc** [comment]
Well it seems that this is game related. And I can't do anything about it right now. Sorry mate
