### ISSUE TITLE
Alien Isolation Saves

### ISSUE THREAD

**Issue by dustovich1** [smaTc/RemotePlayDetached#15]
So I have this installed with my donor game now. When I go to run Alien Isolation, the game loads and runs fine, but gives an error that it cannot access the save files. I have it pointed to the game exe directly, should I be starting this through some sort of steam launch shortcut or something?

**Comment by smaTc** [comment]
I am not sure what you are describing here. What exactly are you trying to achieve? A more detailed explanation please

**Comment by dustovich1** [comment]
![image](https://user-images.githubusercontent.com/17212092/87340343-8b44a580-c50d-11ea-8b08-4946c19ac602.png)
Here is a screenshot.

**Comment by smaTc** [comment]
So just to be sure: you swapped your donor game exe with rpd and launch rpd/donor via steam?

**Comment by dustovich1** [comment]
Yep. I am using 'Chess Sphere' as my donor game, and launch that via Steam. Alien Isolation is also a Steam game, but I am launching the executable directly and not through any sort of Steam magic in RPD. When launched directly by Steam it is not an issue. I don't know if I need to somehow make it full circle and use RPD to get Steam to launch the game or something. This game uses Steam for game saves it looks like, reside right in the Steam\userdata folder in program files.

**Comment by smaTc** [comment]
Please use Fruity Smoothie as donor game and try RPD with an emulator (RetroArch N64 or similar)

**Comment by dustovich1** [comment]
I have download Fruity Smoothie and used that as donor game. Dolphin runs just fine as I would have expected. The issue is not that things will not run, it is accessing the save.

**Comment by smaTc** [comment]
Well that means it is something game specific of Alien Isolation I can't do anything about. Especially Steam Games are hit or miss in most cases. Sorry m8
