### ISSUE TITLE
[Feature Request] Steam Games Integration

### ISSUE THREAD

**Issue by marcussacana** [smaTc/RemotePlayDetached#16]
I'm trying use this to enable the remote play to a steam game that don't allow it, usually I should just add non steam game and run but in my case, who are using linux as host, and the game running under proton, the things became a little weird, for some reason even If i run the same command to launch the game manually, the game freeze, but when I use the steam://run/gameid and the steam is who execute that same command, the game works.
Initially I tried just use the xdg-open to tell the steam start the game, but that don't worked because the xdg-open/steam link are async, this mean after the game start the game the xdg command ends and don't wait to the game close, with that my RemotePlay session is closed and I can't play the game (and he keeps running in the host pc)

I tried this tool trying solve that, but looks like he only allow add commands manually, and this is exactly what I tried before and don't worked, then If possible can you add a small integration with the steam to launch the steam game and wait he closes (linux compatible)?

**Comment by smaTc** [comment]
Sorry for the late response. I am not sure if I am understand your suggestion correctly. Can you give a more detailed explanation?

**Comment by marcussacana** [comment]
A Example, I want play the freeware mmo called Kurtzpel with the RemotePlay,
At least in my machine the kurtzpel don't appear in the remote play game list.
Then I wanted something like a integration with the steam that automatically setup your tool to use with certain steam games, that's all.
