### ISSUE TITLE
PS4 Remote Play

### ISSUE THREAD

**Issue by jazmac** [smaTc/RemotePlayDetached#6]
After playing around with both Breath of the Wild in Cemu and Assassin's Creed Odyssey, I started to think if there was a way I could use this program and allow someone to play through my PS4 with the PS4 remote play feature for PC.

My friend and I nearly got it working as he was able to view PS4 remote play booting up and connecting but as soon as the actual remote play window for the game displayed the PS4 UI (it seems to open up a new window when it does this) steam remote play went into standby mode and he couldn't view or interact with the PS4.

I'm wondering what the issue might be. I recognise you might not be able to test this out though if you don't own a PS4.

**Comment by alx365** [comment]
Interesting thought... This software is full of potential.

**Comment by alx365** [comment]
Maybe start remote play a bit later so that steam knows what window is the right one?

**Comment by smaTc** [comment]
Well these are two streams. From PS4 to PC, Remote Play Host to Remote Play Client. Input lag could be pretty hight. Even though an interesting thought, unfortunately I don't have a PS4 so that I can test it.

**Comment by jazmac** [comment]
Ye. It was more just a could it be done kind of thing, not necessarily a particularly great gaming experience.

I have a capture card so I actually have a way to capture the visual component without using the PS4 remote play anyway using OBS's preview feature (thus eliminating any added input lag) but obviously run into the hurdle of having no way to capture the input.
